#!/usr/bin/env python3
"""Build slim index.html from the backup."""

import os

BASE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(BASE, 'public', 'index.html.bak')
DST = os.path.join(BASE, 'public', 'index.html')

with open(SRC, 'r') as f:
    lines = f.readlines()

out = []

# Head (lines 1-13)
out.extend(lines[0:13])
out.append('    <link rel="stylesheet" href="/css/styles.css">\n')
out.append('</head>\n')
out.append('\n')

# Body tag + main app HTML (lines 2927-3683, 0-indexed: 2926-3682)
out.extend(lines[2926:3683])
out.append('\n')

# Script references
out.append('    <!-- ========== APPLICATION SCRIPTS ========== -->\n')
out.append('    <script src="https://app.omedash.com/socket.io/socket.io.js"></script>\n')
out.append('    <script src="/js/app.js"></script>\n')
out.append('\n')

# Onboarding HTML (lines 5741-5804 incl style attr, skip 5805 document.write, skip 5808-5817 IIFE)
# 0-indexed: 5740-5803 (includes line 5804 which has the style attribute for ageDropdown)
out.extend(lines[5740:5804])
# Add placeholder comment instead of document.write (skipping line 5805)
out.append('                            <!-- Age options generated by onboarding.js -->\n')
# Lines 5806-5807 (0-indexed: 5805-5806) — closing tags after the document.write
out.extend(lines[5805:5807])
# Skip lines 5808-5817 (age dropdown IIFE script), continue with lines 5818-5851
out.extend(lines[5817:5851])
out.append('\n')

# Onboarding & Auth script tags
out.append('    <!-- Onboarding & Auth scripts -->\n')
out.append('    <script src="/js/onboarding.js"></script>\n')
out.append('    <script type="module" src="/js/auth.js"></script>\n')
out.append('</body>\n')
out.append('\n')
out.append('</html>\n')

with open(DST, 'w') as f:
    f.writelines(out)

print(f"Written {len(out)} lines to {DST}")
